use exit code variables

diff --git a/check_cdap_program/bin/check_cdap_program b/check_cdap_program/bin/check_cdap_program
--- a/check_cdap_program/bin/check_cdap_program
+++ b/check_cdap_program/bin/check_cdap_program
@@ -81,6 +81,13 @@ OPT_TIMEOUT=30
 
 API_VERSION='v3'
 
+# Exit codes
+OK=0
+WARNING=1
+CRITICAL=2
+UNKNOWN=3
+
+
 # Results
 res_status=0
 res_message=''
@@ -90,7 +97,7 @@ while getopts "hvu:f:m:s:S:w:W:t:" opt; do
   case $opt in
     h)
       usage
-      exit 0
+      exit ${OK}
       ;;
     v)
       OPT_VERBOSE=1
@@ -122,7 +129,7 @@ while getopts "hvu:f:m:s:S:w:W:t:" opt; do
     \?)
       echo "Invalid option supplied" >&2
       usage
-      exit 1
+      exit ${WARNING}
       ;;
   esac
 done
@@ -131,7 +138,7 @@ done
 if [ -z "${OPT_URI}" ] ; then
   echo "ERROR: -u <uri> is required"
   usage
-  exit 3
+  exit ${UNKNOWN}
 fi
 
 if [ -z ${OPT_FLOWS} ] && [ -z ${OPT_MAPREDUCES} ] && \
@@ -139,7 +146,7 @@ if [ -z ${OPT_FLOWS} ] && [ -z ${OPT_MAPREDUCES} ] && \
    [ -z ${OPT_WORKFLOWS} ] && [ -z ${OPT_WORKERS} ] ; then
   echo "ERROR: Nothing to check. Please provide -f, -m, -s, -S, -w, or -W flags"
   usage
-  exit 3
+  exit ${UNKNOWN}
 fi
 
 # TODO: validate arguments to each of -f,-m,-s,-S,-w,-W are valid,
@@ -149,7 +156,7 @@ fi
 if [ ! "$(which curl)" != "" ] ; then
   echo "ERROR: curl must be installed and present in \$PATH" 
   usage
-  exit 3
+  exit ${UNKNOWN}
 fi
 
 # Convenience wrapper functions for get_program_status
@@ -212,7 +219,7 @@ function cdap_curl_request {
   # Abort Unknown if failed curl execution
   if [[ ${__exitcode} -ne 0 ]] ; then
     echo "UNKNOWN: curl error with exit code ${__exitcode}, output: ${__resp}"
-    exit 3
+    exit ${UNKNOWN}
   fi
 
   # Handle per HTTP response code
@@ -222,15 +229,15 @@ function cdap_curl_request {
       ;;
     401)
       echo "UNKNOWN: CDAP Authentication not currently supported: ${__resp}"
-      exit 3
+      exit ${UNKNOWN}
       ;;
     404)
       echo "CRITICAL: CDAP Endpoint not found ${__respcode}: ${__url}"
-      exit 2
+      exit ${CRITICAL}
       ;;
     *)
       echo "UNKNOWN: unexpected HTTP response code ${__respcode}: ${__resp}"
-      exit 3
+      exit ${UNKNOWN}
       ;;
   esac
 
@@ -258,7 +265,7 @@ function process_result {
 
   # Set cumulative exit status
   if [[ ! ${__status} =~ RUNNING ]] ; then
-    res_status=2
+    res_status=${CRITICAL}
   fi
 }
 
