validate program spec arguments

diff --git a/check_cdap_program/bin/check_cdap_program b/check_cdap_program/bin/check_cdap_program
--- a/check_cdap_program/bin/check_cdap_program
+++ b/check_cdap_program/bin/check_cdap_program
@@ -161,6 +161,36 @@ fi
 # TODO: validate arguments to each of -f,-m,-s,-S,-w,-W are valid,
 #         comma-separated program specifications
 
+# Validates a given program specification is in the format:
+#   App.Prog[,App.Prog, ...]
+#   Input:
+#     Arg1: Program specification: (App.Prog)
+#   Output:
+#     none
+function validate_program_options {
+  local __opt_val=${1}
+  local __prog_specs=''
+  local __prog_spec=''
+  local __appname=''
+  local __progname=''
+  IFS=',' read -ra __prog_specs <<< "${__opt_val}"
+  for __prog_spec in "${__prog_specs[@]}"; do
+  #  validate_program_spec ${__program}
+    IFS='.' read __appname __progname <<< "${__prog_spec}"
+    if [ -z ${__appname} ] || [ -z ${__progname} ] ; then
+      echo "ERROR: Invalid program specification given: ${__opt_val}"
+      usage
+      exit ${CRITICAL}
+    fi
+  done
+}
+
+# Validate arguments to each of -f,-m,-s,-S,-w,-W are valid, comma-separated
+#   program specifications
+for __arg in ${OPT_FLOWS} ${OPT_MAPREDUCES} ${OPT_SERVICES} ${OPT_SPARKS} ${OPT_WORKFLOWS} ${OPT_WORKERS} ; do
+  validate_program_options ${__arg}
+done
+
 # Confirm that curl is installed
 if [[ ! $(which curl) ]] ; then
   echo "ERROR: curl must be installed and present in \$PATH" 
